### ISSUE TITLE
Nueva jerarquía para cabeceras

### ISSUE THREAD

**Issue by arturocandela** [amiguetes/lmsgi-blog#2]
En nuestro documento usamos elementos `<h1>`, `<h2>` y `<h3>` para declarar títulos de diferentes niveles. Los estilos por defecto de estos elementos se
encuentran siempre muy lejos de lo que queremos, por lo que, tenemos que otorgarle los estilos apropiados:

```css
h1 { font: bold 2em verdana, sans-serif; }
h2 { font: bold 1.5em verdana, sans-serif; }
h3 { font: bold 1em verdana, sans-serif; }
```

La propiedad font , asignada a los elementos `<h1>`, `<h2>` y `<h3>`, nos permite declarar todos los estilos para el texto en una sola línea. Las propiedades que pueden ser declaradas usando font son: `font-style`, `font-variant`, `font-weight`, `font-size` y `font-family`. Con las reglas anteriores estamos cambiando el grosor, tamaño y el tipo de letra del texto.
