### ISSUE TITLE
Últimos Retoques

### ISSUE THREAD

**Issue by arturocandela** [amiguetes/lmsgi-blog#9]
Lo único que nos queda por hacer es trabajar en el diseño del contenido:

```css
.article { background: #FFFBCC; border: 1px solid #999999; padding: 20px; margin-bottom: 15px; }
.article_header { border-bottom: 1px solid #999999; }
.article_footer { text-align: right; }
.time { color: #999999; }
.figure { border: 1px double #999999; padding: 5px; }
.figure .figcaption { font: italic 0.6em verdana, sans-serif; }
```

La primera regla referencia los elementos de la clase `article` y les otorga algunos estilos básicos (color de fondo, un borde sólido de 1 pixel, margen interno y margen inferior). El margen inferior de 15 píxeles tiene el propósito de separar un elemento `article` del siguiente verticalmente.

Cada elemento `article` cuenta con un elemento `article_header` que muestra los títulos y fecha de publicación del artículo y un elemento `article_footer` que muestra los comentarios recibidos. El texto de los elementos `article_footer` aparecerá alineado a la derecha, mientras que los elementos `article_header` tendrán un borde inferior.

Los elementos `time` tendrán el color de la fuente `#999999`. En el primer artículo, además, tenemos un elemento `<div class="figure">` que contiene una imagen y un elemento `<div class="figcaption">` que nos muestra un texto explicativo de la misma. Por lo tanto, crearemos dos reglas para aplicar estilos a dichos elementos. En concreto, se pondrá un borde a los elementos `figure` y se cambiará la fuente a los elementos `figcaption`.
